# -*- coding: utf-8 -*-
"""LS-DYNA keyword deck writer.

The writer uses comma-separated free format.  This avoids the silent truncation
that fixed eight-column fields can cause for large IDs and scientific notation.
"""

from __future__ import unicode_literals

from collections import OrderedDict

from .mappings import element_mapping, surface_face
from .model import resolve_named
from .parser import as_float, as_int, joined_data_rows


def fmt(value):
    if value is None:
        return ''
    if isinstance(value, float):
        return '%.12g' % value
    return str(value)


def row(values):
    return ','.join(fmt(value) for value in values)


def clean_title(value, maximum=70):
    value = str(value or '').replace('\r', ' ').replace('\n', ' ').strip()
    return value[:maximum]


def floats_from_block(block):
    result = []
    if block is None:
        return result
    for data_row in joined_data_rows(block):
        for value in data_row:
            if value == '':
                continue
            try:
                result.append(as_float(value))
            except ValueError:
                pass
    return result


class IdPool(object):
    def __init__(self, first=1):
        self.next_id = first

    def take(self):
        value = self.next_id
        self.next_id += 1
        return value


class CardBuffer(object):
    def __init__(self):
        self.lines = []

    def comment(self, value):
        self.lines.append('$ ' + clean_title(value, 150))

    def card(self, keyword, rows=None, title=None, comments=None):
        name = keyword if keyword.startswith('*') else '*' + keyword
        if title:
            name += '_TITLE'
        self.lines.append(name)
        if title:
            self.lines.append(clean_title(title))
        if comments:
            for value in comments:
                self.comment(value)
        for values in rows or []:
            if isinstance(values, (str, bytes)):
                self.lines.append(values)
            else:
                self.lines.append(row(values))

    def extend(self, other):
        self.lines.extend(other.lines)


class MaterialRecord(object):
    def __init__(self, name, mid):
        self.name = name
        self.mid = mid
        self.eosid = 0
        self.cards = CardBuffer()
        self.model = ''


class PartRecord(object):
    def __init__(self, pid, sid, material, title, family, elform, section, instance):
        self.pid = pid
        self.sid = sid
        self.material = material
        self.title = title
        self.family = family
        self.elform = elform
        self.section = section
        self.instance = instance
        self.element_ids = []


class LSDynaWriter(object):
    def __init__(self, flat_model, diagnostics, options=None):
        self.flat = flat_model
        self.source = flat_model.source
        self.diagnostics = diagnostics
        self.options = options or {}
        self.material_ids = IdPool(1)
        self.section_ids = IdPool(1)
        self.part_ids = IdPool(1)
        self.curve_ids = IdPool(1)
        self.node_set_ids = IdPool(1)
        self.segment_set_ids = IdPool(1)
        self.part_set_ids = IdPool(1)
        self.materials = OrderedDict()
        self.parts = []
        self.curves = []
        self.node_set_index = OrderedDict()
        self.segment_set_index = OrderedDict()
        self.part_set_index = OrderedDict()
        self.action_cards = CardBuffer()
        self.id_rows = []
        self._default_material = None
        self._body_part_scope = None
        self.mass_values = {}

    def build(self):
        self._convert_materials()
        self._assign_parts()
        self._index_node_sets()
        self._convert_contacts()
        self._convert_actions()

        deck = CardBuffer()
        deck.card('*KEYWORD')
        deck.card('*TITLE', [[clean_title(self.source.title)]])
        deck.comment('Generated by ATD 1.0; source units are preserved without scaling.')
        self._write_controls(deck)
        for curve in self.curves:
            deck.extend(curve)
        for material in self.materials.values():
            deck.extend(material.cards)
        self._write_sections_and_parts(deck)
        self._write_nodes_and_elements(deck)
        self._write_sets(deck)
        deck.extend(self.action_cards)
        for line in self.options.get('append_cards', []):
            deck.lines.append(str(line))
        deck.card('*END')
        return '\n'.join(deck.lines) + '\n'

    def _material_override(self, name):
        overrides = self.options.get('material_overrides', {})
        return overrides.get(name) or overrides.get(name.upper())

    def _convert_materials(self):
        for name, material in self.source.materials.items():
            record = MaterialRecord(name, self.material_ids.take())
            override = self._material_override(name)
            if override:
                record.eosid = int(override.get('eos_id', 0))
                for line in override.get('cards', []):
                    rendered = str(line).replace('{MID}', str(record.mid))
                    rendered = rendered.replace('{EOSID}', str(record.eosid))
                    record.cards.lines.append(rendered)
                self.diagnostics.info(
                    'MATERIAL_OVERRIDE',
                    'Material %s was emitted from the mapping override.' % name,
                    material.block,
                )
            else:
                self._automatic_material(material, record)
            self.materials[name] = record

    def _automatic_material(self, material, record):
        density_values = floats_from_block(material.first('DENSITY'))
        density = density_values[0] if density_values else 0.0
        elastic = material.first('ELASTIC')
        elastic_values = floats_from_block(elastic)
        elastic_type = (elastic.param('TYPE', 'ISOTROPIC').upper() if elastic else 'ISOTROPIC')
        plastic = material.first('PLASTIC')
        hyper = material.first('HYPERELASTIC')
        drucker = material.first('DRUCKER PRAGER')
        foam = material.first('CRUSHABLE FOAM') or material.first('LOW DENSITY FOAM')
        eos = material.first('EOS') or material.first('EQUATION OF STATE')

        if density == 0.0:
            self.diagnostics.warning(
                'MISSING_DENSITY',
                'Material %s has no density; RO is written as 0 and must be reviewed.' % material.name,
                material.block,
            )

        if eos and not (elastic or plastic or hyper or drucker or foam):
            record.cards.card(
                '*MAT_NULL',
                [[record.mid, density, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
                title=material.name,
                comments=['Abaqus EOS-only material; strength is intentionally null.'],
            )
        elif plastic:
            hardening = plastic.param('HARDENING', 'ISOTROPIC').upper()
            if hardening == 'JOHNSON COOK':
                record.model = 'JOHNSON_COOK'
                self._write_johnson_cook(material, record, density, elastic_values, plastic)
            else:
                self._write_piecewise_plastic(material, record, density, elastic_values, plastic)
                if elastic_type == 'SHEAR':
                    self.diagnostics.error(
                        'EOS_MISES_OVERRIDE_REQUIRED',
                        'Abaqus shear elasticity plus tabular Mises plasticity/EOS needs an LS-DYNA hydro material override.',
                        elastic,
                    )
                if hardening not in ('ISOTROPIC', 'COMBINED'):
                    self.diagnostics.warning(
                        'PLASTIC_APPROXIMATION',
                        '%s hardening for %s was approximated with *MAT_024.' % (
                            hardening, material.name),
                        plastic,
                    )
        elif hyper:
            self._write_hyperelastic(material, record, density, hyper)
        elif drucker:
            values = floats_from_block(drucker)
            e = elastic_values[0] if elastic_values else 0.0
            nu = elastic_values[1] if len(elastic_values) > 1 else 0.0
            padded = values + [0.0] * 8
            record.cards.card(
                '*MAT_DRUCKER_PRAGER',
                [[record.mid, density, e, nu, padded[0], padded[1], padded[2], padded[3]],
                 padded[4:12]],
                title=material.name,
                comments=['Parameter order follows the Abaqus Drucker-Prager table; verify calibration.'],
            )
            self.diagnostics.warning(
                'DRUCKER_PRAGER_REVIEW',
                'Drucker-Prager conventions differ; verify friction/dilation and hardening.',
                drucker,
            )
        elif foam:
            e = elastic_values[0] if elastic_values else 0.0
            nu = elastic_values[1] if len(elastic_values) > 1 else 0.0
            record.cards.card(
                '*MAT_CRUSHABLE_FOAM',
                [[record.mid, density, e, nu, 0.0, 0.0, 0.0, 0.0]],
                title=material.name,
                comments=['Volumetric hardening must be supplied through a material override.'],
            )
            self.diagnostics.error(
                'FOAM_CURVE_REQUIRED',
                'Foam material %s needs an LS-DYNA-specific pressure-volume curve.' % material.name,
                foam,
            )
        elif elastic and elastic_type in ('ENGINEERING CONSTANTS', 'ORTHOTROPIC', 'LAMINA'):
            padded = elastic_values + [0.0] * 12
            record.cards.card(
                '*MAT_ORTHOTROPIC_ELASTIC',
                [[record.mid, density] + padded[0:6], padded[6:12]],
                title=material.name,
            )
            if elastic_type == 'LAMINA':
                self.diagnostics.warning(
                    'LAMINA_ELASTIC_REVIEW',
                    'Abaqus lamina constants were placed in MAT_002; verify transverse constants and material axes.',
                    elastic,
                )
        elif elastic and elastic_type in ('TRACTION', 'ANISOTROPIC'):
            record.cards.card(
                '*MAT_ELASTIC',
                [[record.mid, density, 1.0, 0.3, 0.0, 0.0, 0]],
                title=material.name + ' [PLACEHOLDER]',
                comments=['PLACEHOLDER ONLY - traction/anisotropic elasticity needs a material override.'],
            )
            self.diagnostics.error(
                'ELASTIC_TYPE_NOT_MAPPED',
                'Elastic TYPE=%s for %s has no safe automatic material mapping.' % (
                    elastic_type, material.name),
                elastic,
            )
        elif elastic and elastic_type == 'SHEAR':
            record.cards.card(
                '*MAT_NULL',
                [[record.mid, density, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
                title=material.name + ' [EOS PLACEHOLDER]',
            )
            self.diagnostics.error(
                'SHEAR_STRENGTH_OVERRIDE_REQUIRED',
                'Abaqus ELASTIC, TYPE=SHEAR needs an LS-DYNA hydro strength-law override.',
                elastic,
            )
        elif elastic:
            e = elastic_values[0] if elastic_values else 0.0
            nu = elastic_values[1] if len(elastic_values) > 1 else 0.0
            record.cards.card(
                '*MAT_ELASTIC',
                [[record.mid, density, e, nu, 0.0, 0.0, 0]],
                title=material.name,
            )
        else:
            user_material = material.first('USER MATERIAL')
            record.cards.card(
                '*MAT_ELASTIC',
                [[record.mid, density, 1.0, 0.3, 0.0, 0.0, 0]],
                title=material.name + ' [PLACEHOLDER]',
                comments=['PLACEHOLDER ONLY - replace through material_overrides in JSON.'],
            )
            self.diagnostics.error(
                'MATERIAL_NOT_MAPPED',
                'Material %s has no safely mapped mechanical law%s.' % (
                    material.name, ' (USER MATERIAL)' if user_material else ''),
                material.block,
            )

        if eos:
            self._write_eos(material, record, eos)
            if elastic or plastic or hyper or drucker or foam:
                self.diagnostics.warning(
                    'EOS_STRENGTH_COUPLING',
                    'Material %s combines a strength law and EOS; verify this coupling is supported.' % material.name,
                    eos,
                )
        self._write_failure(material, record)
        self._report_unconsumed_material_properties(material)

    def _write_piecewise_plastic(self, material, record, density, elastic_values, block):
        e = elastic_values[0] if elastic_values else 0.0
        nu = elastic_values[1] if len(elastic_values) > 1 else 0.0
        pairs = []
        for values in joined_data_rows(block):
            numeric = []
            for value in values:
                if value != '':
                    try:
                        numeric.append(as_float(value))
                    except ValueError:
                        pass
            if len(numeric) >= 2:
                pairs.append((numeric[1], numeric[0]))  # plastic strain, true stress
            if len(numeric) > 2:
                self.diagnostics.warning(
                    'PLASTIC_DEPENDENCY_REVIEW',
                    'Temperature/field/rate columns in %s plastic data were not represented by MAT_024.' % material.name,
                    block,
                )
        sigy = pairs[0][1] if pairs else 0.0
        lcid = self._add_curve(material.name + ' plasticity', pairs) if len(pairs) > 1 else 0
        record.cards.card(
            '*MAT_PIECEWISE_LINEAR_PLASTICITY',
            [[record.mid, density, e, nu, sigy, 0.0, 0.0, 0.0],
             [0.0, 0.0, lcid, 0, 0.0, 0.0, 0.0, 0.0]],
            title=material.name,
        )

    def _write_johnson_cook(self, material, record, density, elastic_values, block):
        values = floats_from_block(block) + [0.0] * 8
        rate = material.first('RATE DEPENDENT')
        rate_values = floats_from_block(rate) + [0.0, 1.0]
        elastic = material.first('ELASTIC')
        elastic_type = (elastic.param('TYPE', 'ISOTROPIC').upper() if elastic else 'ISOTROPIC')
        e = elastic_values[0] if elastic_values else 0.0
        nu = elastic_values[1] if len(elastic_values) > 1 else 0.0
        if elastic_type == 'SHEAR':
            shear, e, nu = e, 0.0, 0.0
        else:
            shear = e / (2.0 * (1.0 + nu)) if (e and nu != -1.0) else 0.0
        initiation = material.first('DAMAGE INITIATION')
        criterion = ((initiation.param('CRITERION') or '').upper() if initiation else '')
        damage = floats_from_block(initiation) + [0.0] * 5 if criterion == 'JOHNSON COOK' else [0.0] * 5
        heat = floats_from_block(material.first('SPECIFIC HEAT'))
        cp = heat[0] if heat else 0.0
        rows = [
             [record.mid, density, shear, e, nu, 0.0, 0.0, 0.0],
             [values[0], values[1], values[2], rate_values[0], values[3], values[4], values[5], rate_values[1]],
             [cp, 0.0, 2.0, 0.0, damage[0], damage[1], damage[2], damage[3]],
             [damage[4], 0.0, 1.0 if criterion == 'JOHNSON COOK' else 0.0, 1.0e-6, 0, 0, 0, 0],
        ]
        record.cards.card(
            '*MAT_JOHNSON_COOK',
            rows,
            title=material.name,
            comments=['A,B,n,Tmelt,Ttransition and Johnson-Cook rate data mapped; review temperature units.'],
        )

    def _write_hyperelastic(self, material, record, density, block):
        model = block.param('N', '') or block.param('TYPE', '')
        model = model.upper()
        values = floats_from_block(block) + [0.0] * 8
        if 'OGDEN' in block.header.upper():
            record.cards.card(
                '*MAT_OGDEN_RUBBER',
                [[record.mid, density, values[0], values[1], values[2], values[3], values[4], values[5]]],
                title=material.name,
                comments=['Verify Abaqus/LS-DYNA Ogden coefficient and compressibility conventions.'],
            )
        else:
            record.cards.card(
                '*MAT_MOONEY-RIVLIN_RUBBER',
                [[record.mid, density, values[0], values[1], 0.49, 0.0, 0.0, 0.0]],
                title=material.name,
                comments=['Neo-Hooke/Mooney-Rivlin coefficients mapped; incompressibility set to PR=0.49.'],
            )
        self.diagnostics.warning(
            'HYPERELASTIC_REVIEW',
            'Hyperelastic energy conventions and test-data fitting must be validated.',
            block,
        )

    def _write_eos(self, material, record, block):
        values = floats_from_block(block) + [0.0] * 10
        eos_type = (block.param('TYPE', 'USUP') or 'USUP').upper().replace('-', ' ')
        record.eosid = record.mid
        if eos_type in ('USUP', 'MIE GRUNEISEN', 'GRUNEISEN'):
            record.cards.card(
                '*EOS_GRUNEISEN',
                [[record.eosid] + values[0:7], [values[7]]],
                title=material.name + ' EOS',
            )
        elif eos_type in ('IDEAL GAS', 'IDEAL_GAS'):
            record.cards.card(
                '*EOS_IDEAL_GAS',
                [[record.eosid] + values[0:7]],
                title=material.name + ' EOS',
            )
        elif eos_type in ('POLYNOMIAL', 'LINEAR POLYNOMIAL'):
            record.cards.card(
                '*EOS_LINEAR_POLYNOMIAL',
                [[record.eosid] + values[0:7], values[7:10]],
                title=material.name + ' EOS',
            )
        else:
            self.diagnostics.error(
                'EOS_NOT_MAPPED',
                'EOS type %s for %s requires a material override.' % (eos_type, material.name),
                block,
            )

    def _write_failure(self, material, record):
        initiation = material.first('DAMAGE INITIATION')
        fail_strain = material.first('FAIL STRAIN') or material.first('SHEAR FAILURE')
        if not initiation and not fail_strain:
            return
        source = initiation or fail_strain
        values = floats_from_block(source)
        effective = values[0] if values else 0.0
        criterion = (source.param('CRITERION', 'DUCTILE') or 'DUCTILE').upper()
        if criterion == 'JOHNSON COOK' and record.model == 'JOHNSON_COOK':
            if material.first('DAMAGE EVOLUTION'):
                self.diagnostics.warning(
                    'JOHNSON_COOK_EVOLUTION_REDUCED',
                    'Abaqus progressive damage evolution for %s was reduced to MAT_015 erosion at failure.' % material.name,
                    material.first('DAMAGE EVOLUTION'),
                )
            return
        record.cards.card(
            '*MAT_ADD_EROSION',
            [[record.mid, 0.0, 0.0, 0.0, effective, 0.0, 1.0, 1.0],
             [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
            comments=['Abaqus %s initiation reduced to an effective-strain erosion threshold.' % criterion],
        )
        evolution = material.first('DAMAGE EVOLUTION')
        if evolution or criterion not in ('DUCTILE', 'SHEAR'):
            self.diagnostics.warning(
                'DAMAGE_APPROXIMATION',
                'Damage evolution/stress-state dependence for %s is not equivalent to scalar EFFEPS.' % material.name,
                source,
            )

    def _report_unconsumed_material_properties(self, material):
        consumed = set([
            'DENSITY', 'ELASTIC', 'PLASTIC', 'RATE DEPENDENT', 'HYPERELASTIC',
            'DRUCKER PRAGER', 'DRUCKER PRAGER HARDENING', 'CRUSHABLE FOAM',
            'LOW DENSITY FOAM', 'EOS', 'EQUATION OF STATE', 'DAMAGE INITIATION',
            'DAMAGE EVOLUTION', 'FAIL STRAIN', 'SHEAR FAILURE',
        ])
        plastic = material.first('PLASTIC')
        if plastic and (plastic.param('HARDENING') or '').upper() == 'JOHNSON COOK':
            consumed.add('SPECIFIC HEAT')
        for keyword, blocks in material.properties.items():
            if keyword not in consumed:
                self.diagnostics.error(
                    'MATERIAL_PROPERTY_NOT_MAPPED',
                    '*%s in material %s was not converted; use material_overrides.' % (
                        keyword, material.name),
                    blocks[0],
                )

    def _add_curve(self, title, points):
        cid = self.curve_ids.take()
        card = CardBuffer()
        data = [[cid, 0, 1.0, 1.0, 0.0, 0.0, 0, 0]]
        data.extend([[x, y] for x, y in points])
        card.card('*DEFINE_CURVE', data, title=title)
        self.curves.append(card)
        return cid

    def _default_material_record(self):
        if self._default_material:
            return self._default_material
        record = MaterialRecord('__ATD_UNASSIGNED__', self.material_ids.take())
        record.cards.card(
            '*MAT_ELASTIC',
            [[record.mid, 0.0, 1.0, 0.3, 0.0, 0.0, 0]],
            title='ATD UNASSIGNED PLACEHOLDER',
            comments=['Invalid placeholder: assign an Abaqus material/section before solving.'],
        )
        self.materials[record.name] = record
        self._default_material = record
        return record

    def _assign_parts(self):
        assignment = {}
        for instance, section in self.flat.section_assignments:
            key = instance + '.' + section.elset
            element_ids = self.flat.elsets.get(key)
            if element_ids is None:
                element_ids = resolve_named(self.flat.elsets, section.elset)
            if element_ids is None:
                self.diagnostics.error(
                    'SECTION_SET_MISSING',
                    'Section references missing ELSET %s.' % section.elset,
                    section.block,
                )
                continue
            for eid in element_ids:
                if eid in assignment:
                    self.diagnostics.warning(
                        'MULTIPLE_SECTIONS',
                        'Element %s has multiple section assignments; the last one wins.' % eid,
                        section.block,
                    )
                assignment[eid] = section

        groups = OrderedDict()
        overrides = self.options.get('element_type_overrides', {})
        for eid, element in self.flat.elements.items():
            mapping = element_mapping(element.element_type, overrides)
            if mapping is None:
                self.diagnostics.error(
                    'ELEMENT_TYPE_NOT_MAPPED',
                    'Element type %s is not mapped; element %s was omitted.' % (
                        element.element_type, element.source_label),
                    element.block,
                )
                continue
            family, elform, expected = mapping
            if len(element.nodes) != expected:
                self.diagnostics.error(
                    'CONNECTIVITY_COUNT',
                    '%s expects %s nodes, got %s for element %s.' % (
                        element.element_type, expected, len(element.nodes), element.source_label),
                    element.block,
                )
                continue
            section = assignment.get(eid)
            if family == 'mass':
                values = []
                if section:
                    for value in section.values:
                        if value != '':
                            try:
                                values.append(as_float(value))
                            except ValueError:
                                pass
                if not values:
                    self.diagnostics.error(
                        'MASS_VALUE_MISSING',
                        'Point mass element %s has no *MASS value.' % element.source_label,
                        element.block,
                    )
                    continue
                self.mass_values[eid] = values[0]
                element.pid = 0
                continue
            material_name = section.material if section else ''
            material = self.materials.get(material_name)
            if material is None:
                material = self._default_material_record()
                self.diagnostics.error(
                    'UNASSIGNED_MATERIAL',
                    'Element %s (%s) has no mapped material/section.' % (
                        element.source_label, element.instance),
                    element.block,
                )
            key = (element.instance, id(section), family, elform, material.mid)
            if key not in groups:
                sid = self.section_ids.take()
                pid = self.part_ids.take()
                title = '%s / %s / %s' % (
                    element.instance,
                    section.elset if section else 'UNASSIGNED',
                    element.element_type,
                )
                groups[key] = PartRecord(
                    pid, sid, material, title, family, elform, section, element.instance
                )
            part = groups[key]
            part.element_ids.append(eid)
            element.pid = part.pid
        self.parts = list(groups.values())
        for part in self.parts:
            if (part.family in ('solid', 'solid10') and
                    part.material.model == 'JOHNSON_COOK' and not part.material.eosid):
                self.diagnostics.error(
                    'JOHNSON_COOK_SOLID_NEEDS_EOS',
                    'Solid part %s uses MAT_015 without an EOS; add Abaqus *EOS or a material override.' % part.title,
                    part.section.block if part.section else None,
                )

    def _index_node_sets(self):
        for name, values in self.flat.nsets.items():
            if values and name not in self.node_set_index:
                self.node_set_index[name] = self.node_set_ids.take()

    def _node_set_id(self, name, block=None):
        key = str(name).strip().upper()
        if key in self.node_set_index:
            return self.node_set_index[key]
        matches = [(candidate, sid) for candidate, sid in self.node_set_index.items()
                   if candidate.endswith('.' + key)]
        if len(matches) == 1:
            return matches[0][1]
        self.diagnostics.error('NODE_SET_MISSING', 'Cannot resolve node set %s.' % name, block)
        return None

    def _surface_segments(self, surface_name, block):
        key, surface = self._find_surface(surface_name)
        if surface is None:
            self.diagnostics.error('SURFACE_MISSING', 'Cannot resolve surface %s.' % surface_name, block)
            return []
        if surface.surface_type not in ('ELEMENT', ''):
            self.diagnostics.error(
                'NODE_SURFACE_UNSUPPORTED',
                'Node-based surface %s cannot safely become a segment set.' % surface_name,
                surface.block,
            )
            return []
        segments = []
        for values in surface.rows:
            clean = [value for value in values if value != '']
            if len(clean) < 2:
                continue
            target = clean[0].strip().upper()
            face = clean[1].strip().upper()
            if surface.scope and '.' not in target:
                target = surface.scope + '.' + target
            element_ids = self.flat.elsets.get(target)
            if element_ids is None:
                element_ids = resolve_named(self.flat.elsets, target)
            if element_ids is None:
                try:
                    source_eid = as_int(target)
                    mapped = self.flat.element_map.get((surface.scope or 'GLOBAL', source_eid))
                    element_ids = [mapped] if mapped else []
                except ValueError:
                    element_ids = []
            for eid in element_ids:
                element = self.flat.elements.get(eid)
                if element is None:
                    continue
                nodes = surface_face(element.element_type, face, element.nodes)
                if nodes is None:
                    self.diagnostics.error(
                        'FACE_NOT_MAPPED',
                        'Face %s of %s cannot be converted for surface %s.' % (
                            face, element.element_type, surface_name),
                        surface.block,
                    )
                else:
                    segments.append(nodes)
        return segments

    def _find_surface(self, surface_name):
        key = str(surface_name).strip().upper()
        surface = self.flat.surfaces.get(key)
        if surface is None:
            matches = [value for name, value in self.flat.surfaces.items()
                       if name.endswith('.' + key)]
            if len(matches) == 1:
                surface = matches[0]
        return key, surface

    def _node_surface_set_id(self, surface_name, block):
        key, surface = self._find_surface(surface_name)
        if surface is None:
            self.diagnostics.error('SURFACE_MISSING', 'Cannot resolve surface %s.' % surface_name, block)
            return None
        virtual_name = '@SURFACE.' + key
        if virtual_name in self.node_set_index:
            return self.node_set_index[virtual_name]
        nodes = []
        for values in surface.rows:
            clean = [value for value in values if value != '']
            if not clean:
                continue
            target = clean[0].strip().upper()
            if surface.scope and '.' not in target:
                target = surface.scope + '.' + target
            selected = resolve_named(self.flat.nsets, target)
            if selected is None:
                try:
                    source_nid = as_int(target)
                    mapped = self.flat.node_map.get((surface.scope or 'GLOBAL', source_nid))
                    selected = [mapped] if mapped else []
                except ValueError:
                    selected = []
            nodes.extend(selected)
        nodes = list(OrderedDict((nid, None) for nid in nodes).keys())
        if not nodes:
            self.diagnostics.error(
                'NODE_SURFACE_EMPTY',
                'Node surface %s did not resolve to any nodes.' % surface_name,
                surface.block,
            )
            return None
        self.flat.nsets[virtual_name] = nodes
        sid = self.node_set_ids.take()
        self.node_set_index[virtual_name] = sid
        return sid

    def _contact_surface_ref(self, surface_name, block):
        key, surface = self._find_surface(surface_name)
        if surface is None:
            self.diagnostics.error('SURFACE_MISSING', 'Cannot resolve surface %s.' % surface_name, block)
            return None
        if surface.surface_type == 'NODE':
            sid = self._node_surface_set_id(key, block)
            return (sid, 4) if sid is not None else None
        sid = self._segment_set_id(key, block)
        return (sid, 0) if sid is not None else None

    def _segment_set_id(self, name, block):
        key = str(name).strip().upper()
        if key in self.segment_set_index:
            return self.segment_set_index[key][0]
        segments = self._surface_segments(key, block)
        if not segments:
            return None
        sid = self.segment_set_ids.take()
        self.segment_set_index[key] = (sid, segments)
        return sid

    def _friction(self, interaction_name):
        interaction = self.source.interactions.get(str(interaction_name or '').strip().upper())
        if interaction:
            blocks = interaction.properties.get('FRICTION', [])
            if blocks:
                values = floats_from_block(blocks[0])
                if values:
                    return values[0]
        return as_float(self.options.get('contact_defaults', {}).get('friction', 0.0), 0.0)

    def _contact_rows(self, block):
        return [values for values in joined_data_rows(block)
                if len([value for value in values if value != '']) >= 2]

    def _convert_contacts(self):
        general_contact = False
        general_interaction = ''
        property_assignments = []
        for action in self.source.actions:
            block = action.block
            if action.kind == 'CONTACT INCLUSIONS':
                all_exterior = block.has_flag('ALL EXTERIOR') or any(
                    'ALL EXTERIOR' in ','.join(values).upper()
                    for values in joined_data_rows(block)
                )
                if all_exterior or not block.data:
                    general_contact = True
                else:
                    self.diagnostics.error(
                        'CONTACT_INCLUSION_NOT_MAPPED',
                        'Selective general-contact inclusions require explicit contact pairs.',
                        block,
                    )
            elif action.kind == 'CONTACT PROPERTY ASSIGNMENT':
                for values in joined_data_rows(block):
                    clean = [value for value in values if value != '']
                    if clean:
                        property_assignments.append(clean)
                        general_interaction = clean[-1].strip().upper()
            elif action.kind in ('CONTACT PAIR', 'TIE'):
                for values in self._contact_rows(block):
                    clean = [value for value in values if value != '']
                    slave = self._contact_surface_ref(clean[0], block)
                    master = self._contact_surface_ref(clean[1], block)
                    if slave is None or master is None:
                        continue
                    if slave[1] == 4 and master[1] == 0:
                        keyword = ('*CONTACT_TIED_NODES_TO_SURFACE' if action.kind == 'TIE'
                                   else '*CONTACT_AUTOMATIC_NODES_TO_SURFACE')
                    elif slave[1] == 0 and master[1] == 0:
                        keyword = ('*CONTACT_TIED_SURFACE_TO_SURFACE' if action.kind == 'TIE'
                                   else '*CONTACT_AUTOMATIC_SURFACE_TO_SURFACE')
                    else:
                        self.diagnostics.error(
                            'CONTACT_SURFACE_TYPES',
                            'The master side must be element-based; node-to-node contact is not mapped.',
                            block,
                        )
                        continue
                    friction = self._friction(block.param('INTERACTION'))
                    soft = int(self.options.get('contact_defaults', {}).get('soft', 2))
                    self.action_cards.card(
                        keyword,
                        [[slave[0], master[0], slave[1], master[1], 0, 0, 0, 0],
                         [friction, friction, 0.0, 0.0, 0.0, 0, 0.0, 1.0e20],
                         [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                         [soft, 0.0, 0, 0, 0, 0, 0, 1]],
                        title=clean_title(block.param('NAME') or action.kind),
                    )
        if general_contact:
            if len(property_assignments) > 1 or any(len(values) > 1 for values in property_assignments):
                self.diagnostics.error(
                    'REGIONAL_CONTACT_PROPERTIES',
                    'Region-specific general-contact property assignments cannot be reduced to one global contact.',
                    next((action.block for action in self.source.actions
                          if action.kind == 'CONTACT PROPERTY ASSIGNMENT'), None),
                )
            friction = self._friction(general_interaction)
            soft = int(self.options.get('contact_defaults', {}).get('soft', 2))
            self.action_cards.card(
                '*CONTACT_AUTOMATIC_SINGLE_SURFACE',
                [[0, 0, 0, 0, 0, 0, 0, 0],
                 [friction, friction, 0.0, 0.0, 0.0, 0, 0.0, 1.0e20],
                 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                 [soft, 0.0, 0, 0, 0, 0, 0, 1]],
                title='Abaqus general contact - all exterior',
            )
        self._report_interaction_properties()

    def _report_interaction_properties(self):
        for interaction in self.source.interactions.values():
            for keyword, blocks in interaction.properties.items():
                if keyword == 'FRICTION':
                    values = floats_from_block(blocks[0])
                    if len(values) > 1:
                        self.diagnostics.warning(
                            'FRICTION_TABLE_REDUCED',
                            'Only the first coefficient in interaction %s was mapped to FS/FD.' % interaction.name,
                            blocks[0],
                        )
                elif keyword in ('NORMAL BEHAVIOR', 'SURFACE BEHAVIOR'):
                    if blocks[0].data or (blocks[0].param('PRESSURE-OVERCLOSURE') or 'HARD').upper() != 'HARD':
                        self.diagnostics.warning(
                            'NORMAL_CONTACT_REVIEW',
                            'Normal behavior for %s was reduced to LS-DYNA automatic penalty contact.' % interaction.name,
                            blocks[0],
                        )
                else:
                    self.diagnostics.error(
                        'INTERACTION_PROPERTY_NOT_MAPPED',
                        '*%s in interaction %s requires a project-specific LS-DYNA contact definition.' % (
                            keyword, interaction.name),
                        blocks[0],
                    )

    def _step_times(self, action):
        step = self.source.steps.get(action.step_name)
        if step:
            return step.start_time, step.start_time + step.period
        total = sum(value.period for value in self.source.steps.values()) or 1.0
        return 0.0, total

    def _amplitude_points(self, block, magnitude, action):
        amplitude_name = str(block.param('AMPLITUDE') or '').strip().upper()
        start, end = self._step_times(action)
        if amplitude_name and amplitude_name in self.source.amplitudes:
            amplitude = self.source.amplitudes[amplitude_name]
            definition = (amplitude.param('DEFINITION') or 'TABULAR').upper()
            if definition not in ('TABULAR', 'SMOOTH STEP'):
                self.diagnostics.error(
                    'AMPLITUDE_DEFINITION_NOT_MAPPED',
                    'Amplitude %s uses DEFINITION=%s; only TABULAR/SMOOTH STEP can be reduced to a curve.' % (
                        amplitude_name, definition),
                    amplitude,
                )
                return [(start, magnitude), (end, magnitude)]
            if definition == 'SMOOTH STEP':
                self.diagnostics.warning(
                    'SMOOTH_STEP_LINEARIZED',
                    'Amplitude %s smooth interpolation was reduced to piecewise linear points.' % amplitude_name,
                    amplitude,
                )
            values = floats_from_block(amplitude)
            points = []
            for index in range(0, len(values) - 1, 2):
                time_value = values[index]
                if amplitude.param('TIME', 'STEP TIME').upper() != 'TOTAL TIME':
                    time_value += start
                points.append((time_value, values[index + 1] * magnitude))
            if points:
                return points
        step = self.source.steps.get(action.step_name)
        ramp = bool(step and ((step.block.param('AMPLITUDE') or '').upper() == 'RAMP'
                              or step.procedure == 'STATIC'))
        return [(start, 0.0 if ramp else magnitude), (end, magnitude)]

    def _target_node(self, value):
        try:
            return as_int(value)
        except ValueError:
            return None

    def _boundary_dofs(self, values):
        if len(values) < 2:
            return [], 0.0
        symbolic = str(values[1]).strip().upper()
        symbolic_map = {
            'ENCASTRE': [1, 2, 3, 4, 5, 6], 'PINNED': [1, 2, 3],
            'XSYMM': [1, 5, 6], 'YSYMM': [2, 4, 6], 'ZSYMM': [3, 4, 5],
            'XASYMM': [2, 3, 4], 'YASYMM': [1, 3, 5], 'ZASYMM': [1, 2, 6],
        }
        if symbolic in symbolic_map:
            return symbolic_map[symbolic], 0.0
        try:
            first = as_int(values[1])
            last = as_int(values[2]) if len(values) > 2 and values[2] != '' else first
            magnitude = as_float(values[3], 0.0) if len(values) > 3 else 0.0
            return list(range(first, last + 1)), magnitude
        except ValueError:
            return [], 0.0

    def _convert_actions(self):
        for action in self.source.actions:
            block = action.block
            if action.kind == 'BOUNDARY':
                self._write_boundaries(action)
            elif action.kind == 'CLOAD':
                self._write_cloads(action)
            elif action.kind == 'DLOAD':
                self._write_dloads(action)
            elif action.kind == 'DSLOAD':
                self._write_dsloads(action)
            elif action.kind == 'INITIAL CONDITIONS':
                self._write_initial_conditions(action)
            elif action.kind == 'TEMPERATURE':
                self.diagnostics.error(
                    'TEMPERATURE_NOT_MAPPED',
                    'Temperature fields require a thermal material/control mapping.', block)
            elif action.kind == 'RIGID BODY':
                self.diagnostics.error(
                    'RIGID_BODY_REVIEW',
                    '*RIGID BODY requires an explicit MAT_RIGID/constraint choice in LS-DYNA.', block)

    def _write_boundaries(self, action):
        block = action.block
        motion_type = (block.param('TYPE') or 'DISPLACEMENT').upper()
        vad = {'VELOCITY': 0, 'ACCELERATION': 1, 'DISPLACEMENT': 2}.get(motion_type)
        if vad is None:
            self.diagnostics.error(
                'BOUNDARY_TYPE_NOT_MAPPED',
                'Boundary TYPE=%s is not mapped.' % motion_type,
                block,
            )
            return
        if (block.param('OP') or '').upper() == 'NEW':
            self.diagnostics.warning(
                'BOUNDARY_OP_NEW',
                'Abaqus OP=NEW removal semantics are not represented in the single LS-DYNA deck.',
                block,
            )
        for values in joined_data_rows(block):
            clean = list(values)
            if not clean or not clean[0]:
                continue
            dofs, magnitude = self._boundary_dofs(clean)
            if not dofs:
                self.diagnostics.error('BAD_BOUNDARY', 'Cannot parse boundary row %s.' % clean, block)
                continue
            node = self._target_node(clean[0])
            if magnitude == 0.0:
                flags = [1 if dof in dofs else 0 for dof in range(1, 7)]
                if node is not None:
                    mapped = self.flat.node_map.get(('GLOBAL', node), node)
                    self.action_cards.card('*BOUNDARY_SPC_NODE', [[mapped, 0] + flags])
                else:
                    sid = self._node_set_id(clean[0], block)
                    if sid is not None:
                        self.action_cards.card('*BOUNDARY_SPC_SET', [[sid, 0] + flags])
            else:
                target_id = node if node is not None else self._node_set_id(clean[0], block)
                if target_id is None:
                    continue
                for dof in dofs:
                    points = self._amplitude_points(block, magnitude, action)
                    curve = self._add_curve('%s prescribed DOF %s' % (clean[0], dof), points)
                    keyword = ('*BOUNDARY_PRESCRIBED_MOTION_NODE' if node is not None
                               else '*BOUNDARY_PRESCRIBED_MOTION_SET')
                    if node is not None:
                        target_id = self.flat.node_map.get(('GLOBAL', node), node)
                    self.action_cards.card(keyword, [[target_id, dof, vad, curve, 1.0, 0, 1.0e20, 0.0]])

    def _write_cloads(self, action):
        block = action.block
        for values in joined_data_rows(block):
            clean = [value for value in values if value != '']
            if len(clean) < 3:
                self.diagnostics.error('BAD_CLOAD', 'Cannot parse concentrated load row %s.' % values, block)
                continue
            try:
                dof = as_int(clean[1])
                magnitude = as_float(clean[2])
            except ValueError:
                self.diagnostics.error('BAD_CLOAD', 'Invalid CLOAD numeric data %s.' % values, block)
                continue
            curve = self._add_curve('%s load DOF %s' % (clean[0], dof),
                                    self._amplitude_points(block, 1.0, action))
            node = self._target_node(clean[0])
            if node is not None:
                node = self.flat.node_map.get(('GLOBAL', node), node)
                self.action_cards.card('*LOAD_NODE_POINT', [[node, dof, curve, magnitude, 0, 0, 0, 0]])
            else:
                sid = self._node_set_id(clean[0], block)
                if sid is not None:
                    self.action_cards.card('*LOAD_NODE_SET', [[sid, dof, curve, magnitude, 0, 0, 0, 0]])

    def _write_dloads(self, action):
        block = action.block
        for values in joined_data_rows(block):
            clean = [value for value in values if value != '']
            if len(clean) < 3:
                continue
            load_type = clean[1].upper()
            if load_type == 'GRAV' and len(clean) >= 6:
                if not self._ensure_body_load_scope(clean[0], block):
                    continue
                magnitude = as_float(clean[2], 0.0)
                direction = [as_float(value, 0.0) for value in clean[3:6]]
                curve = self._add_curve('gravity', self._amplitude_points(block, 1.0, action))
                for axis, component in zip(('X', 'Y', 'Z'), direction):
                    if component:
                        self.action_cards.card('*LOAD_BODY_' + axis, [[curve, magnitude * component]])
            elif load_type.startswith('P'):
                self.diagnostics.error(
                    'ELEMENT_PRESSURE_NEEDS_SURFACE',
                    'Element-face DLOAD %s should be expressed as *DSLOAD on a named surface.' % load_type,
                    block,
                )
            else:
                self.diagnostics.error('DLOAD_NOT_MAPPED', 'DLOAD type %s is not mapped.' % load_type, block)

    def _ensure_body_load_scope(self, elset_name, block):
        element_ids = resolve_named(self.flat.elsets, elset_name)
        if element_ids is None:
            self.diagnostics.error(
                'BODY_LOAD_SET_MISSING',
                'Gravity target ELSET %s cannot be resolved.' % elset_name,
                block,
            )
            return False
        pids = sorted(set(self.flat.elements[eid].pid for eid in element_ids
                          if eid in self.flat.elements and self.flat.elements[eid].pid is not None))
        all_pids = sorted(part.pid for part in self.parts)
        if pids == all_pids:
            scope = ('ALL', tuple(pids))
        else:
            scope = ('PARTS', tuple(pids))
        if self._body_part_scope is not None and self._body_part_scope != scope:
            self.diagnostics.error(
                'MULTIPLE_BODY_LOAD_SCOPES',
                'LS-DYNA *LOAD_BODY_PARTS is global; multiple different Abaqus gravity scopes need manual cards.',
                block,
            )
            return False
        if self._body_part_scope is None:
            self._body_part_scope = scope
            if scope[0] == 'PARTS':
                name = '@BODY.' + str(elset_name).strip().upper()
                sid = self.part_set_ids.take()
                self.part_set_index[name] = (sid, pids)
                self.action_cards.card('*LOAD_BODY_PARTS', [[sid]])
        return True

    def _write_dsloads(self, action):
        block = action.block
        for values in joined_data_rows(block):
            clean = [value for value in values if value != '']
            if len(clean) < 3:
                continue
            load_type = clean[1].upper()
            if not load_type.startswith('P'):
                self.diagnostics.error('DSLOAD_NOT_MAPPED', 'DSLOAD type %s is not mapped.' % load_type, block)
                continue
            sid = self._segment_set_id(clean[0], block)
            if sid is None:
                continue
            magnitude = as_float(clean[2], 0.0)
            curve = self._add_curve('%s pressure' % clean[0], self._amplitude_points(block, 1.0, action))
            self.action_cards.card('*LOAD_SEGMENT_SET', [[sid, curve, magnitude, 0.0]])

    def _write_initial_conditions(self, action):
        block = action.block
        condition_type = (block.param('TYPE') or '').upper()
        if condition_type != 'VELOCITY':
            self.diagnostics.error(
                'INITIAL_CONDITION_NOT_MAPPED',
                'Initial condition TYPE=%s is not mapped.' % condition_type,
                block,
            )
            return
        for values in joined_data_rows(block):
            clean = list(values)
            if len(clean) < 2:
                continue
            vector = []
            for value in clean[1:7]:
                vector.append(as_float(value, 0.0) if value != '' else 0.0)
            while len(vector) < 6:
                vector.append(0.0)
            node = self._target_node(clean[0])
            if node is not None:
                nodes = [self.flat.node_map.get(('GLOBAL', node), node)]
            else:
                nodes = resolve_named(self.flat.nsets, clean[0]) or []
            for node_id in nodes:
                self.action_cards.card('*INITIAL_VELOCITY_NODE', [[node_id] + vector])

    def _write_controls(self, deck):
        end_time = sum(step.period for step in self.source.steps.values())
        if not end_time:
            end_time = as_float(self.options.get('termination_time', 1.0), 1.0)
        deck.card('*CONTROL_TERMINATION', [[end_time, 0, 0.0, 0.0, 0.0]])
        deck.card('*CONTROL_TIMESTEP', [[0.0, 0.67, 0, 0.0, 0.0, 0, 0, 0]])
        procedures = set(step.procedure for step in self.source.steps.values())
        if procedures.intersection(set(['STATIC', 'IMPLICIT_DYNAMIC'])):
            initial_dt = end_time / 100.0 if end_time else 0.01
            deck.card('*CONTROL_IMPLICIT_GENERAL', [[1, initial_dt]])
            deck.card('*CONTROL_IMPLICIT_SOLUTION', [[12, 11, 15, 0.0, 0.0, 0.0, 0.0]])
            if len(procedures) > 1:
                self.diagnostics.warning(
                    'MIXED_PROCEDURES',
                    'Mixed Abaqus step procedures were reduced to global LS-DYNA controls.',
                )
        interval = as_float(self.options.get('d3plot_interval', 0.0), 0.0)
        if interval <= 0.0:
            interval = end_time / 20.0 if end_time else 0.05
        deck.card('*DATABASE_BINARY_D3PLOT', [[interval]])
        deck.card('*DATABASE_GLSTAT', [[interval]])
        deck.card('*DATABASE_MATSUM', [[interval]])

    def _write_sections_and_parts(self, deck):
        for part in self.parts:
            section = part.section
            values = []
            if section:
                for value in section.values:
                    if value != '':
                        try:
                            values.append(as_float(value))
                        except ValueError:
                            pass
            if part.family in ('solid', 'solid10'):
                deck.card('*SECTION_SOLID', [[part.sid, part.elform, 0]], title=part.title)
            elif part.family in ('shell', 'plane_strain', 'plane_stress', 'axisymmetric'):
                thickness = values[0] if values else 1.0
                if not values and part.family == 'shell':
                    self.diagnostics.warning(
                        'DEFAULT_SHELL_THICKNESS',
                        'Shell part %s had no thickness; 1.0 was used.' % part.title,
                        section.block if section else None,
                    )
                deck.card(
                    '*SECTION_SHELL',
                    [[part.sid, part.elform, 0.833333, 5, 1.0, 0.0, 0, 1],
                     [thickness, thickness, thickness, thickness, 0.0, 0.0, 0.0, 0.0]],
                    title=part.title,
                )
            elif part.family == 'beam':
                dims = (values + [1.0, 1.0])[:2]
                deck.card(
                    '*SECTION_BEAM',
                    [[part.sid, part.elform, 1.0, 2, 0.0, 0.0],
                     [dims[0], dims[1], dims[0], dims[1]]],
                    title=part.title,
                )
            deck.card(
                '*PART',
                [[part.pid, part.sid, part.material.mid, part.material.eosid, 0, 0, 0, 0]],
                title=part.title,
            )

    def _write_nodes_and_elements(self, deck):
        node_rows = []
        for nid, coords in self.flat.nodes.items():
            node_rows.append([nid, coords[0], coords[1], coords[2], 0, 0])
        deck.card('*NODE', node_rows)
        for (instance, source_id), target_id in self.flat.node_map.items():
            self.id_rows.append(['NODE', instance, source_id, target_id])

        families = OrderedDict()
        for eid, element in self.flat.elements.items():
            if element.pid is None:
                continue
            mapping = element_mapping(
                element.element_type, self.options.get('element_type_overrides', {})
            )
            if mapping is None:
                continue
            family = mapping[0]
            values = list(element.nodes)
            keyword = None
            if family == 'solid':
                keyword = 'SOLID'
                if len(values) < 8:
                    values.extend([values[-1]] * (8 - len(values)))
            elif family == 'solid10':
                keyword = 'SOLID10'
            elif family in ('shell', 'plane_strain', 'plane_stress', 'axisymmetric'):
                keyword = '*ELEMENT_SHELL'
                if len(values) == 3:
                    values.append(values[-1])
            elif family == 'beam':
                keyword = '*ELEMENT_BEAM'
                values = values[:2] + [0]
            elif family == 'mass':
                keyword = '*ELEMENT_MASS'
                values = [values[0], self.mass_values[eid]]
            if keyword:
                if keyword == 'SOLID10':
                    families.setdefault(keyword, []).extend([[eid, element.pid], values])
                elif keyword == '*ELEMENT_MASS':
                    families.setdefault(keyword, []).append([eid] + values)
                else:
                    families.setdefault(keyword, []).append([eid, element.pid] + values)
                self.id_rows.append(['ELEMENT', element.instance, element.source_label, eid])
        for keyword, values in families.items():
            deck.card('*ELEMENT_SOLID' if keyword in ('SOLID', 'SOLID10') else keyword, values)

    def _write_set_rows(self, deck, keyword, sid, values, title):
        rows = [[sid, 0.0, 0.0, 0.0, 0.0]]
        for index in range(0, len(values), 8):
            rows.append(values[index:index + 8])
        deck.card(keyword, rows, title=title)

    def _write_sets(self, deck):
        reverse_node_sets = dict((sid, name) for name, sid in self.node_set_index.items())
        for sid in sorted(reverse_node_sets):
            name = reverse_node_sets[sid]
            self._write_set_rows(deck, '*SET_NODE_LIST', sid, self.flat.nsets[name], name)
        for name, (sid, segments) in self.segment_set_index.items():
            rows = [[sid, 0.0, 0.0, 0.0, 0.0]]
            rows.extend(segments)
            deck.card('*SET_SEGMENT', rows, title=name)
        for name, (sid, pids) in self.part_set_index.items():
            self._write_set_rows(deck, '*SET_PART_LIST', sid, pids, name)
